import {
  Activity,
  BarChart3,
  FileText,
  FileUser,
  FolderKanban,
  Images,
  Inbox,
  LayoutDashboard,
  LayoutList,
  Mail,
  Menu,
  MessageSquareQuote,
  PhoneCall,
  Search,
  Settings,
  Sparkles,
  UserRound,
  Users,
  Wrench,
} from 'lucide-react';

export const PATHS = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/',
  PROJECTS: '/projects',
  PROJECT_NEW: '/projects/new',
  PROJECT_VIEW: '/projects/:id/view',
  PROJECT_EDIT: '/projects/:id/edit',
  BLOG: '/blog',
  BLOG_NEW: '/blog/new',
  BLOG_VIEW: '/blog/:id/view',
  BLOG_EDIT: '/blog/:id/edit',
  BLOG_COMMENTS: '/blog/comments',
  PAGES: '/pages',
  PAGES_NEW: '/pages/new',
  PAGES_EDIT: '/pages/:id/edit',
  MENUS: '/menus',
  SERVICES: '/services',
  SERVICE_VIEW: '/services/:id/view',
  SKILLS: '/skills',
  TESTIMONIALS: '/testimonials',
  MESSAGES: '/messages',
  RESUME: '/resume',
  MEDIA: '/media',
  ANALYTICS: '/analytics',
  SEO: '/seo',
  NEWSLETTER: '/newsletter',
  CONTACT_INFO: '/contact-info',
  ACTIVITY: '/activity',
  USERS: '/users',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile',
};

export const NAV_ITEMS = [
  {
    sectionKey: 'nav.overview',
    items: [
      { labelKey: 'nav.dashboard', path: PATHS.DASHBOARD, icon: LayoutDashboard },
      { labelKey: 'nav.analytics', path: PATHS.ANALYTICS, icon: BarChart3 },
      { labelKey: 'nav.messages', path: PATHS.MESSAGES, icon: Inbox, badge: 'New' },
    ],
  },
  {
    sectionKey: 'nav.content',
    items: [
      { labelKey: 'nav.projects', path: PATHS.PROJECTS, icon: FolderKanban },
      { labelKey: 'nav.pages', path: PATHS.PAGES, icon: LayoutList },
      { labelKey: 'nav.menus', path: PATHS.MENUS, icon: Menu },
      { labelKey: 'nav.blog', path: PATHS.BLOG, icon: FileText },
      { labelKey: 'nav.services', path: PATHS.SERVICES, icon: Wrench },
      { labelKey: 'nav.skills', path: PATHS.SKILLS, icon: Sparkles },
      { labelKey: 'nav.testimonials', path: PATHS.TESTIMONIALS, icon: MessageSquareQuote },
    ],
  },
  {
    sectionKey: 'nav.personal',
    items: [
      { labelKey: 'nav.resume', path: PATHS.RESUME, icon: FileUser },
      { labelKey: 'nav.media', path: PATHS.MEDIA, icon: Images },
      { labelKey: 'nav.newsletter', path: PATHS.NEWSLETTER, icon: Mail },
      { labelKey: 'nav.contactInfo', path: PATHS.CONTACT_INFO, icon: PhoneCall },
      { labelKey: 'nav.seo', path: PATHS.SEO, icon: Search },
      { labelKey: 'nav.users', path: PATHS.USERS, icon: Users },
      { labelKey: 'nav.activity', path: PATHS.ACTIVITY, icon: Activity, adminOnly: true },
      { labelKey: 'nav.settings', path: PATHS.SETTINGS, icon: Settings },
    ],
  },
];
