[program:laravel-horizon]
process_name=%(program_name)s
command=php {{PROJECT_PATH}}/artisan horizon
autostart=true
autorestart=true
user={{USER}}
redirect_stderr=true
stdout_logfile={{PROJECT_PATH}}/storage/logs/horizon.log
stopwaitsecs=3600