[program:laravel-reverb]
process_name=%(program_name)s
command=php {{PROJECT_PATH}}/artisan reverb:start
autostart=true
autorestart=true
user={{USER}}
redirect_stderr=true
stdout_logfile={{PROJECT_PATH}}/storage/logs/reverb.log
stopwaitsecs=3600