<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $posts = [
            [
                'title' => '10 React Performance Optimization Techniques Every Developer Should Know in 2024',
                'slug' => 'react-performance-optimization-techniques',
                'category' => 'Performance',
                'cover_icon' => 'bxl-react',
                'cover_gradient' => 'linear-gradient(135deg,#0d0d2b 0%,#1a1a3e 30%,#0a1628 60%,#12121a 100%)',
                'excerpt' => 'Deep dive into advanced React optimization strategies — from code splitting and lazy loading to memoization, virtualization, and concurrent features that can dramatically improve your app\'s performance.',
                'content' => '<p>Performance optimization is one of the most critical aspects of building production React applications. A slow app frustrates users and directly impacts your business metrics — every 100ms delay in load time can reduce conversions by 1%. In this comprehensive guide, we\'ll cover 10 battle-tested techniques that I\'ve used across 50+ React projects to achieve consistently high performance scores.</p><h2>1. React.memo and useMemo — Prevent Unnecessary Re-renders</h2><p>Re-renders are the #1 performance killer in React apps. React.memo wraps a component and prevents it from re-rendering when its props haven\'t changed. useMemo memoizes expensive computations so they only recalculate when dependencies change.</p><h2>2. Code Splitting — Load Only What\'s Needed</h2><p>Code splitting divides your JavaScript bundle into smaller chunks loaded on demand. React provides React.lazy and Suspense for this purpose. Combined with dynamic imports, this can dramatically reduce your initial bundle size.</p><h2>3. Virtual Scrolling for Large Lists</h2><p>Rendering thousands of DOM elements simultaneously destroys performance. Virtual scrolling renders only items visible in the viewport. Libraries like react-window and @tanstack/virtual make this straightforward — achieving 90% DOM reduction with 10K items while maintaining smooth 60fps scrolling.</p><h2>4. useCallback — Stable Function References</h2><p>When you pass callback functions as props, they create new references on every render, causing child components to unnecessarily re-render even when wrapped in React.memo. useCallback returns a memoized version of the callback that only changes when dependencies change.</p><h2>5. Avoid Anonymous Functions in JSX</h2><p>Anonymous functions in JSX create new function instances on every render, breaking memoization. Extract them to stable references using useCallback or define them outside the component.</p><h2>6. Lazy Loading Images</h2><p>Images are often the largest assets on a page. Use native lazy loading with loading="lazy", IntersectionObserver, or libraries like react-lazyload to defer loading off-screen images. This alone can dramatically improve your LCP score.</p><h2>7. Optimize State Management</h2><p>Keep state as local as possible — global state causes entire component trees to re-render. Split large contexts into smaller, focused ones. Consider using useReducer for complex state logic and libraries like Zustand or Jotai for minimal global state overhead.</p><h2>8. Web Workers for Heavy Computations</h2><p>Move CPU-intensive work off the main thread using Web Workers. Data parsing, image processing, and complex calculations should never block the UI thread. The comlink library makes working with Web Workers in React extremely ergonomic.</p><h2>9. Bundle Optimization</h2><p>Analyze your bundle with tools like webpack-bundle-analyzer or Vite\'s rollup-plugin-visualizer. Common wins include replacing heavy libraries with lighter alternatives, using tree-shaking friendly imports, and setting up proper chunk splitting.</p><h2>10. React 18 Concurrent Features</h2><p>React 18 introduced game-changing concurrent features. useTransition lets you mark state updates as non-urgent, keeping the UI responsive. useDeferredValue defers updating non-critical parts of the UI. These features can make your app feel instantaneous.</p><h2>Conclusion</h2><p>Performance optimization is a continuous process, not a one-time task. Start by measuring — you can\'t optimize what you can\'t measure. Profile your app with React DevTools, Chrome Performance panel, and Lighthouse, then systematically apply these techniques where they\'ll have the most impact.</p><p>The most important lesson: ship first, optimize second. A slow app that solves a real problem is infinitely better than a perfectly optimized app that never launches.</p>',
                'tags' => ['React', 'Performance', 'JavaScript', 'Web Dev', 'Optimization'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 8,
                'views' => '4.2K',
                'likes' => 312,
                'featured' => true,
                'published_at' => '2024-12-15 09:00:00',
            ],
            [
                'title' => 'Mastering CSS Grid: From Basic Layouts to Complex Designs',
                'slug' => 'mastering-css-grid',
                'category' => 'CSS',
                'cover_icon' => 'bx-paint',
                'cover_gradient' => 'linear-gradient(135deg,#1a2e1a,#0d1a0d)',
                'excerpt' => 'A comprehensive guide to CSS Grid covering everything from basic concepts to advanced techniques for building complex, responsive layouts without frameworks.',
                'content' => '<p>CSS Grid has fundamentally changed how we build layouts on the web. Unlike Flexbox, which is one-dimensional, Grid gives us full control over both rows and columns simultaneously. This guide takes you from the fundamentals to advanced patterns you can use today.</p><h2>Getting Started with Grid Containers</h2><p>Everything begins with display: grid on a parent container. Its direct children automatically become grid items. From there you define the tracks with grid-template-columns and grid-template-rows, mixing fixed, flexible (fr), and auto-sized tracks.</p><h2>The 12-Column System</h2><p>Most design systems are built on a 12-column grid because 12 divides evenly by 1, 2, 3, 4, and 6. With repeat(12, 1fr) and explicit placement using grid-column: span, you can compose any layout without a single media query breaking it.</p><h2>Advanced Placement</h2><p>Named lines, named areas, and auto-flow dense packing give you surgical control over where items land. Grid areas in particular let you describe an entire page layout in plain English, making templates dramatically more readable.</p><h2>Responsive Without Media Queries</h2><p>Auto-fit and auto-fill combined with minmax() create fluid grids that reflow automatically as the viewport changes. This single technique replaces dozens of breakpoint overrides.</p><p>Once you\'ve mastered these patterns, you\'ll rarely reach for a CSS framework again.</p>',
                'tags' => ['CSS', 'Layout'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 6,
                'views' => '2.1K',
                'likes' => 180,
                'featured' => false,
                'published_at' => '2024-12-10 09:00:00',
            ],
            [
                'title' => 'Building a Production-Ready REST API with Node.js, Express & PostgreSQL',
                'slug' => 'production-ready-rest-api-node-express-postgresql',
                'category' => 'Node.js',
                'cover_icon' => 'bx-server',
                'cover_gradient' => 'linear-gradient(135deg,#1a2a1a,#0a1a0a)',
                'excerpt' => 'Step-by-step tutorial on building a secure, scalable REST API with authentication, rate limiting, input validation, and comprehensive error handling.',
                'content' => '<p>Most tutorials stop at "it works on my machine". This one doesn\'t. We\'ll build a REST API you\'d actually be comfortable shipping to production — with authentication, rate limiting, validation, structured errors, and tests.</p><h2>Project Structure That Scales</h2><p>Separate concerns from day one: routes, controllers, services, and data-access layers. Keeping business logic out of controllers is what lets the API grow without turning into a tangled mess.</p><h2>Validation First</h2><p>Never trust the wire. Validate every request at the boundary with a library like Zod, and return consistent, machine-readable error responses. This is the single highest-leverage thing you can do for API reliability.</p><h2>Authentication Done Right</h2><p>Stateless JWT auth with short-lived access tokens and rotating refresh tokens strikes the right balance between security and usability. Store only hashes, never raw secrets.</p><h2>Rate Limiting & Hardening</h2><p>Add rate limiting per IP and per user, set secure headers, and add request logging with request IDs. These simple layers turn a vulnerable prototype into something you can sleep through.</p><h2>Testing & Observability</h2><p>Cover the critical paths with integration tests, add structured logging, and expose a /health endpoint for your orchestrator. Deploy with confidence by making failures loud and traceable.</p>',
                'tags' => ['Node.js', 'API'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 10,
                'views' => '3.4K',
                'likes' => 245,
                'featured' => false,
                'published_at' => '2024-12-05 09:00:00',
            ],
            [
                'title' => 'Building Scalable Design Systems: Lessons from Enterprise Projects',
                'slug' => 'scalable-design-systems',
                'category' => 'Design',
                'cover_icon' => 'bx-palette',
                'cover_gradient' => 'linear-gradient(135deg,#2a1a2a,#1a0a1a)',
                'excerpt' => 'How to create and maintain a robust design system that scales across multiple products and teams, with real-world lessons from enterprise implementation.',
                'content' => '<p>A design system is more than a component library. It\'s the single source of truth that keeps a dozen teams shipping interfaces that feel like one product. Here are the lessons I\'ve learned building them at enterprise scale.</p><h2>Tokens Before Components</h2><p>Start with design tokens — color, type, spacing, radius. Everything else derives from them. When tokens are the foundation, theming and dark mode become configuration, not surgery.</p><h2>One Source of Truth</h2><p>Components must live in exactly one package and be consumed everywhere. Versioned releases with changelogs let teams upgrade on their own schedule without breaking each other.</p><h2>Documentation Is the Product</h2><p>Without great docs, your system becomes a rumor. Every component needs live examples, prop tables, and guidance on when to use it — and just as importantly, when not to.</p><h2>Governance Over Process</h2><p>Decide how changes get in: contribution guidelines, a review board, and a clear deprecation path. A system without governance decays into a zoo of one-off components.</p><p>Invest early, and the payoff compounds: faster shipping, fewer bugs, and interfaces users actually recognize.</p>',
                'tags' => ['Design', 'Figma'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 7,
                'views' => '1.7K',
                'likes' => 150,
                'featured' => false,
                'published_at' => '2024-11-28 09:00:00',
            ],
            [
                'title' => 'Next.js 14 App Router: Everything You Need to Know',
                'slug' => 'nextjs-14-app-router',
                'category' => 'React',
                'cover_icon' => 'bxl-react',
                'cover_gradient' => 'linear-gradient(135deg,#1a1a2e,#0a0a20)',
                'excerpt' => 'Complete guide to Next.js 14\'s App Router — Server Components, streaming, parallel routes, intercepting routes, and the new metadata API.',
                'content' => '<p>Next.js 14\'s App Router is a paradigm shift. Server Components run on the server by default, giving you faster loads and smaller bundles, while the rest of the React ecosystem keeps working the way you expect.</p><h2>Server Components by Default</h2><p>Move data fetching and rendering to the server, where it belongs. Your client bundle shrinks, your page loads faster, and you can safely use secrets and databases in components without exposing them.</p><h2>Streaming with Suspense</h2><p>Stream every part of your page the moment it\'s ready. Wrap slow, non-critical sections in Suspense boundaries and let the fast parts render first — no more blank screens waiting on one slow query.</p><h2>Parallel & Intercepting Routes</h2><p>Parallel routes render multiple independent views in the same layout — perfect for dashboards. Intercepting routes power patterns like modals that deep-link to their own URL, keeping shareability intact.</p><h2>The New Metadata API</h2><p>Exporting metadata and generateMetadata gives you full control over SEO tags, Open Graph, and canonical URLs per route, statically or dynamically.</p><p>Adopting the App Router is a learning curve, but it pays for itself in performance and developer experience.</p>',
                'tags' => ['Next.js', 'React'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 9,
                'views' => '5.6K',
                'likes' => 402,
                'featured' => false,
                'published_at' => '2024-11-20 09:00:00',
            ],
            [
                'title' => 'From $30/hr to $150/hr: My Freelance Developer Journey',
                'slug' => 'freelance-developer-journey',
                'category' => 'Career',
                'cover_icon' => 'bx-briefcase',
                'cover_gradient' => 'linear-gradient(135deg,#2a1a0a,#1a0a00)',
                'excerpt' => 'Honest story of how I grew my freelance income 5x in 3 years — the strategies, mistakes, client acquisition tactics, and mindset shifts that made it possible.',
                'content' => '<p>Three years ago I was charging $30/hr and constantly underbidding myself. Today I bill $150/hr with a waitlist. This isn\'t a flex — it\'s a roadmap, including the mistakes I hope you\'ll skip.</p><h2>Stop Selling Hours</h2><p>The first shift was psychological: I stopped selling time and started selling outcomes. Clients don\'t buy 40 hours; they buy a store that converts, a dashboard that loads instantly, a product that ships.</p><h2>Niche Down Hard</h2><p>Being a "full-stack generalist" means competing with everyone. When I specialized in e-commerce and SaaS dashboards, the same skills suddenly commanded premium rates from clients who needed exactly that.</p><h2>Results Over Effort</h2><p>I documented every project\'s before/after metrics. A portfolio of "I improved conversion by 40%" sells infinitely better than a portfolio of "I built this with React".</p><h2>Raise Prices on the Way Out</h2><p>Every raise was scarier than the last, and every raise lost a few clients — and those were exactly the clients I didn\'t want. The ones who stayed valued the work, not the discount.</p><p>Your rate is a signal. Raise it, and the market repositions you accordingly.</p>',
                'tags' => ['Career', 'Freelance'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 5,
                'views' => '8.9K',
                'likes' => 615,
                'featured' => false,
                'published_at' => '2024-11-15 09:00:00',
            ],
            [
                'title' => 'Advanced CSS Animations and Micro-interactions That Delight Users',
                'slug' => 'advanced-css-animations-micro-interactions',
                'category' => 'CSS',
                'cover_icon' => 'bx-magic-wand',
                'cover_gradient' => 'linear-gradient(135deg,#1a2a2a,#0a1a1a)',
                'excerpt' => 'Master CSS animations, transitions, and micro-interactions with practical examples and performance optimization techniques for buttery-smooth UIs.',
                'content' => '<p>Micro-interactions are the secret sauce of delightful interfaces. A button that responds the moment it\'s pressed, a card that lifts as you hover, a success state that feels earned — these details separate memorable products from functional ones.</p><h2>Design the Motion, Then Code It</h2><p>Great animation is intentional. Define easing curves that match your brand, keep durations short (150–300ms is the sweet spot), and always respect prefers-reduced-motion for users who need stillness.</p><h2>Transform and Opacity Only</h2><p>The golden rule of performance: animate only transform and opacity. The browser composites those on the GPU. Animating width, height, or top triggers expensive layout and paint on every frame.</p><h2>Easing Makes or Breaks It</h2><p>Default ease feels robotic. Cubic-bezier curves that start fast and ease out — like the popular ease-out-quint — make motion feel physical and satisfying.</p><h2>Micro-interaction Patterns That Work</h2><p>Hover lifts, pressed states, animated feedback on form validation, skeleton loaders, and staggered entrances. Each one guides attention and makes the interface feel alive and responsive.</p><p>Start small: pick one interaction, make it feel great, then move to the next.</p>',
                'tags' => ['CSS', 'Animation'],
                'author' => 'Abu Saleh',
                'author_avatar' => 'AS',
                'author_role' => 'Senior Full-Stack Developer',
                'read_minutes' => 8,
                'views' => '2.6K',
                'likes' => 210,
                'featured' => false,
                'published_at' => '2024-11-08 09:00:00',
            ],
        ];

        foreach ($posts as $post) {
            Post::updateOrCreate(['slug' => $post['slug']], $post);
        }
    }
}
