<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'title' => 'E-Commerce Platform',
                'slug' => 'e-commerce-platform',
                'categories' => ['web', 'fullstack'],
                'description' => 'Full-stack e-commerce solution with real-time inventory management, Stripe payment integration, and an admin dashboard.',
                'image' => 'projects/projects-1.jpg',
                'tags' => ['React', 'Node.js', 'MongoDB', 'Stripe'],
                'year' => '2024',
                'badge' => 'Featured',
                'featured' => true,
                'rating' => 4.9,
                'views' => '2.4K',
                'client' => 'FashionHub Inc.',
                'duration' => '12 Weeks',
                'completed' => 'March 2024',
                'budget' => '$15,000 – $20,000',
                'tech_stack' => [
                    'React / Next.js', 'Node.js / Express', 'PostgreSQL',
                    'Redis Cache', 'AWS (EC2, S3, CloudFront)', 'Stripe Payments',
                ],
                'gallery' => ['projects/projects-1.jpg'],
                'overview' => 'This full-stack e-commerce platform was built for a client in the fashion industry who needed a scalable, modern online store capable of handling thousands of concurrent users. The project involved complete UI/UX design, frontend development, backend API construction, and DevOps setup. The platform features real-time inventory management, a sophisticated product recommendation engine powered by user behavior data, seamless Stripe payment processing, and a comprehensive admin dashboard for managing products, orders, and customers.',
                'challenge' => 'The client needed to migrate from a legacy Magento system that was slow and difficult to maintain. The new platform needed to handle 10,000+ products, support multiple currencies, and process thousands of daily transactions reliably.',
                'solution' => 'Built with Next.js for SSR performance, Node.js microservices for scalability, and PostgreSQL with Redis caching. Implemented a CDN strategy that reduced load times by 73% and set up auto-scaling on AWS to handle traffic spikes.',
                'results' => [
                    ['value' => '73%', 'label' => 'Faster Load Time'],
                    ['value' => '+124%', 'label' => 'Conversion Rate'],
                    ['value' => '99.9%', 'label' => 'Uptime Achieved'],
                    ['value' => '10K+', 'label' => 'Products Managed'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 1,
            ],
            [
                'title' => 'Fitness Tracker App',
                'slug' => 'fitness-tracker-app',
                'categories' => ['mobile', 'design'],
                'description' => 'Cross-platform mobile app with AI-powered workout recommendations, real-time health tracking, and social challenges.',
                'image' => 'projects/projects-2.jpg',
                'tags' => ['React Native', 'Firebase', 'Figma'],
                'year' => '2024',
                'badge' => null,
                'featured' => false,
                'rating' => 4.8,
                'views' => '1.8K',
                'client' => 'AppVenture',
                'duration' => '14 Weeks',
                'completed' => 'February 2024',
                'budget' => '$12,000 – $18,000',
                'tech_stack' => ['React Native', 'Firebase', 'Figma', 'Redux'],
                'gallery' => ['projects/projects-2.jpg'],
                'overview' => 'A cross-platform fitness tracking application built with React Native that helps users monitor workouts, track health metrics in real time, and participate in social challenges. The app holds a 4.9-star rating on both the App Store and Google Play, with AI-powered workout recommendations tailored to each user.',
                'challenge' => 'The client wanted a native-quality experience on both iOS and Android from a single codebase, with real-time health tracking that performs flawlessly even with constant sensor data flowing in.',
                'solution' => 'Built with React Native and Firebase, using an offline-first architecture with progressive data sync. The AI workout recommendation engine personalizes plans based on user history, fitness goals, and performance data.',
                'results' => [
                    ['value' => '4.9', 'label' => 'App Store Rating'],
                    ['value' => '200K+', 'label' => 'Active Users'],
                    ['value' => '60fps', 'label' => 'UI Performance'],
                    ['value' => '2M+', 'label' => 'Workouts Logged'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 2,
            ],
            [
                'title' => 'SaaS Analytics Dashboard',
                'slug' => 'saas-analytics-dashboard',
                'categories' => ['saas', 'web', 'design'],
                'description' => 'Real-time analytics platform with beautiful data visualizations, comprehensive reporting, and team collaboration tools.',
                'image' => 'projects/projects-3.jpg',
                'tags' => ['Next.js', 'Tailwind', 'PostgreSQL'],
                'year' => '2023',
                'badge' => 'Award',
                'featured' => false,
                'rating' => 5.0,
                'views' => '3.1K',
                'client' => 'DataFlow Analytics',
                'duration' => '10 Weeks',
                'completed' => 'January 2024',
                'budget' => '$20,000 – $25,000',
                'tech_stack' => ['Next.js', 'Tailwind CSS', 'PostgreSQL', 'D3.js', 'Redis'],
                'gallery' => ['projects/projects-3.jpg'],
                'overview' => 'A real-time analytics dashboard that has completely transformed how the client team works. Beautiful, intuitive data visualizations with comprehensive reporting and team collaboration tools. Won the 2023 Developer Award for best SaaS product.',
                'challenge' => 'The client needed to process and visualize large volumes of data in real time, replacing slow manual reporting with a fast, interactive dashboard their team would actually use.',
                'solution' => 'Built a real-time analytics platform with D3.js visualizations, streaming data pipelines, team collaboration features, and automated report generation. The intuitive data visualizations improved team productivity by 40%.',
                'results' => [
                    ['value' => '+40%', 'label' => 'Team Productivity'],
                    ['value' => '200ms', 'label' => 'Dashboard Response'],
                    ['value' => '5M+', 'label' => 'Events / Day'],
                    ['value' => '1', 'label' => 'Developer Award'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 3,
            ],
            [
                'title' => 'AI Writing Assistant',
                'slug' => 'ai-writing-assistant',
                'categories' => ['web', 'fullstack', 'saas'],
                'description' => 'GPT-4 powered writing platform with real-time collaboration, version history, and multi-language support.',
                'image' => 'projects/projects-4.jpg',
                'tags' => ['React', 'OpenAI', 'Node.js'],
                'year' => '2024',
                'badge' => 'New',
                'featured' => false,
                'rating' => 4.7,
                'views' => '1.2K',
                'client' => 'Indie SaaS Launch',
                'duration' => '8 Weeks',
                'completed' => 'October 2024',
                'budget' => '$10,000 – $15,000',
                'tech_stack' => ['React', 'OpenAI API', 'Node.js', 'Socket.io'],
                'gallery' => ['projects/projects-4.jpg'],
                'overview' => 'A GPT-4 powered collaborative writing tool with real-time sync, version history, and multi-language support. Currently serving 5K+ active monthly users, the platform combines AI assistance with a clean, distraction-free writing experience.',
                'challenge' => 'Build an AI-assisted writing tool that feels instant and collaborative, streaming GPT-4 responses without blocking user typing or breaking real-time multi-user sync.',
                'solution' => 'Architected a React frontend with Socket.io for real-time collaboration and an OpenAI-powered backend that streams completions. Version history and multi-language support round out the product.',
                'results' => [
                    ['value' => '5K+', 'label' => 'Monthly Users'],
                    ['value' => '12', 'label' => 'Languages Supported'],
                    ['value' => '40%', 'label' => 'Faster Writing'],
                    ['value' => '99.8%', 'label' => 'API Uptime'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 4,
            ],
            [
                'title' => 'Travel Booking Platform',
                'slug' => 'travel-booking-platform',
                'categories' => ['design', 'web'],
                'description' => 'Full-featured travel booking platform with real-time availability, dynamic pricing, and integrated payment gateway.',
                'image' => 'projects/projects-5.jpg',
                'tags' => ['Vue.js', 'Laravel', 'MySQL'],
                'year' => '2023',
                'badge' => null,
                'featured' => false,
                'rating' => 4.6,
                'views' => '987',
                'client' => 'TravelNow',
                'duration' => '10 Weeks',
                'completed' => 'September 2023',
                'budget' => '$18,000 – $22,000',
                'tech_stack' => ['Vue.js', 'Laravel', 'MySQL', 'Redis'],
                'gallery' => ['projects/projects-5.jpg'],
                'overview' => 'Built from scratch in just 10 weeks, this travel booking platform handles thousands of bookings daily without any issues. Real-time availability, dynamic pricing, and an integrated payment gateway power the entire booking flow.',
                'challenge' => 'The client needed a booking platform that could handle thousands of daily transactions with real-time availability while keeping the booking experience fast and reliable.',
                'solution' => 'Combined a Vue.js frontend with a Laravel backend and MySQL, using Redis for real-time availability caching and dynamic pricing logic.',
                'results' => [
                    ['value' => '10K+', 'label' => 'Bookings / Day'],
                    ['value' => '99.9%', 'label' => 'Uptime'],
                    ['value' => '10wks', 'label' => 'Time to Launch'],
                    ['value' => '0', 'label' => 'Downtime Events'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 5,
            ],
            [
                'title' => 'Food Delivery App',
                'slug' => 'food-delivery-app',
                'categories' => ['mobile', 'fullstack'],
                'description' => 'Real-time food delivery mobile application with live order tracking, restaurant management, and driver dashboard.',
                'image' => 'projects/projects-6.jpg',
                'tags' => ['React Native', 'Node.js', 'Socket.io'],
                'year' => '2023',
                'badge' => null,
                'featured' => false,
                'rating' => 4.9,
                'views' => '2.1K',
                'client' => 'Regional Food Startup',
                'duration' => '16 Weeks',
                'completed' => 'August 2023',
                'budget' => '$25,000 – $30,000',
                'tech_stack' => ['React Native', 'Node.js', 'Socket.io', 'PostgreSQL'],
                'gallery' => ['projects/projects-6.jpg'],
                'overview' => 'A real-time food delivery mobile application with live order tracking, restaurant management tools, and a dedicated driver dashboard. Three separate apps (customer, restaurant, driver) share one scalable backend.',
                'challenge' => 'Coordinate customers, restaurants, and drivers in real time while keeping order status accurate down to the second during peak delivery hours.',
                'solution' => 'Used Socket.io for live order tracking across three React Native apps backed by Node.js and PostgreSQL, with geolocation-driven dispatch logic.',
                'results' => [
                    ['value' => '3', 'label' => 'Apps in One System'],
                    ['value' => '50K+', 'label' => 'Orders Delivered'],
                    ['value' => '4.9', 'label' => 'Store Rating'],
                    ['value' => '<2s', 'label' => 'Live Status Updates'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 6,
            ],
            [
                'title' => 'Brand Identity Design',
                'slug' => 'brand-identity-design',
                'categories' => ['design'],
                'description' => 'Complete brand identity system including logo, typography, color palette, and brand guidelines for a tech startup.',
                'image' => 'projects/projects-7.png',
                'tags' => ['Figma', 'Illustrator', 'Branding'],
                'year' => '2023',
                'badge' => null,
                'featured' => false,
                'rating' => 5.0,
                'views' => '1.5K',
                'client' => 'BrandCo',
                'duration' => '6 Weeks',
                'completed' => 'October 2023',
                'budget' => '$8,000 – $12,000',
                'tech_stack' => ['Figma', 'Illustrator', 'Brand Strategy'],
                'gallery' => ['projects/projects-7.png'],
                'overview' => 'An incredible brand identity system created for a startup: modern, cohesive, and perfectly representative of the company values. The Figma design system is incredibly well organized and makes it easy for the internal team to maintain brand consistency.',
                'challenge' => 'The startup needed a complete identity — logo, typography, color palette, and guidelines — that could scale from launch materials to product UI without losing cohesion.',
                'solution' => 'Delivered a full brand system with a scalable Figma design system, comprehensive guidelines, and production-ready assets across all touchpoints.',
                'results' => [
                    ['value' => '1', 'label' => 'Complete Identity'],
                    ['value' => '40+', 'label' => 'Brand Assets'],
                    ['value' => '100%', 'label' => 'Brand Consistency'],
                    ['value' => '6wks', 'label' => 'Delivery Time'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 7,
            ],
            [
                'title' => 'Project Management Tool',
                'slug' => 'project-management-tool',
                'categories' => ['saas', 'web'],
                'description' => 'Collaborative project management platform with Kanban boards, time tracking, team chat, and automated reporting.',
                'image' => 'projects/projects-8.jpg',
                'tags' => ['React', 'GraphQL', 'PostgreSQL'],
                'year' => '2022',
                'badge' => null,
                'featured' => false,
                'rating' => 4.8,
                'views' => '876',
                'client' => 'Remote Dev Studio',
                'duration' => '12 Weeks',
                'completed' => 'December 2022',
                'budget' => '$15,000 – $20,000',
                'tech_stack' => ['React', 'GraphQL', 'PostgreSQL', 'Redis'],
                'gallery' => ['projects/projects-8.jpg'],
                'overview' => 'A collaborative project management platform with Kanban boards, time tracking, team chat, and automated reporting — designed for distributed teams that live in their browser.',
                'challenge' => 'Distributed teams needed a tool combining task tracking, time tracking, and communication in one fast interface with reliable real-time updates.',
                'solution' => 'Built with React and GraphQL over PostgreSQL, with Redis-backed presence and real-time board updates so every teammate sees changes instantly.',
                'results' => [
                    ['value' => '1.5K+', 'label' => 'Teams Using It'],
                    ['value' => '99.9%', 'label' => 'Uptime'],
                    ['value' => '200ms', 'label' => 'Avg. Response'],
                    ['value' => '8+', 'label' => 'Integrations'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 8,
            ],
            [
                'title' => 'Crypto Portfolio Tracker',
                'slug' => 'crypto-portfolio-tracker',
                'categories' => ['web', 'fullstack'],
                'description' => 'Real-time cryptocurrency portfolio tracker with price alerts, tax reporting, and DeFi protocol integrations.',
                'image' => 'projects/projects-9.jpg',
                'tags' => ['Next.js', 'Web3.js', 'Redis'],
                'year' => '2022',
                'badge' => null,
                'featured' => false,
                'rating' => 4.5,
                'views' => '1.1K',
                'client' => 'Web3 Startup',
                'duration' => '10 Weeks',
                'completed' => 'November 2022',
                'budget' => '$12,000 – $16,000',
                'tech_stack' => ['Next.js', 'Web3.js', 'Redis', 'PostgreSQL'],
                'gallery' => ['projects/projects-9.jpg'],
                'overview' => 'A real-time cryptocurrency portfolio tracker with price alerts, tax reporting, and DeFi protocol integrations. Pulls live market data and wallet balances into a single, actionable dashboard.',
                'challenge' => 'Aggregate real-time market data and on-chain wallet balances from multiple sources while keeping the UI fast and price alerts accurate.',
                'solution' => 'Next.js frontend with Web3.js for chain data, Redis for caching live market feeds, and PostgreSQL for historical portfolio and tax records.',
                'results' => [
                    ['value' => '15+', 'label' => 'Exchanges Connected'],
                    ['value' => '<1s', 'label' => 'Live Prices'],
                    ['value' => '4.5', 'label' => 'User Rating'],
                    ['value' => '3', 'label' => 'DeFi Protocols'],
                ],
                'demo_url' => '#',
                'repo_url' => '#',
                'sort_order' => 9,
            ],
        ];

        foreach ($projects as $project) {
            Project::updateOrCreate(['slug' => $project['slug']], $project);
        }
    }
}
